/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#5d5d63",
        "surface-container-high": "#e7e8ea",
        "background": "#f8f9fb",
        "surface-variant": "#e1e2e4",
        "surface-bright": "#f8f9fb",
        "inverse-on-surface": "#f0f1f3",
        "on-secondary-fixed-variant": "#6a18a0",
        "on-tertiary-container": "#ffffff",
        "on-background": "#191c1e",
        "inverse-surface": "#2e3132",
        "secondary-container": "#c579fd",
        "on-tertiary-fixed": "#1a1b20",
        "primary-fixed-dim": "#c1c1ff",
        "on-secondary-fixed": "#2e004d",
        "inverse-primary": "#c1c1ff",
        "tertiary-container": "#76767c",
        "surface-container-highest": "#e1e2e4",
        "on-surface": "#191c1e",
        "surface": "#f8f9fb",
        "surface-container": "#edeef0",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#8438ba",
        "primary": "#4744e5",
        "on-primary-fixed-variant": "#2c24ce",
        "primary-container": "#6161ff",
        "on-secondary-container": "#510080",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#09006b",
        "secondary-fixed-dim": "#e2b6ff",
        "surface-container-low": "#f3f4f6",
        "on-tertiary-fixed-variant": "#46464c",
        "on-error": "#ffffff",
        "primary-fixed": "#e1dfff",
        "secondary-fixed": "#f3daff",
        "tertiary-fixed-dim": "#c6c6cc",
        "surface-tint": "#4745e5",
        "surface-dim": "#d9dadc",
        "on-primary-container": "#ffffff",
        "on-surface-variant": "#464555",
        "tertiary-fixed": "#e3e2e8",
        "error-container": "#ffdad6",
        "outline": "#767587",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
};
